name: Deploy documentation

# Check for reference:
# https://github.com/s1rius/ezlog/blob/20dce11e6d324bb18f57dc7c7c6d4a8bf40064de/.github/workflows/publish_pages.yml

on:
  schedule:
    - cron: "40 03 */2 * *" # Runs at 03:40, every 2 days
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: pages
  cancel-in-progress: true

env:
  runner: ubuntu-latest
  cache-mkdocs-key: cache-mkdocs
  REPO_URL: https://github.com/KyleGospo/docs.bazzite.gg
  SITE_URL: https://docs.bazzite.gg

jobs:
  deploy:
    permissions:
      contents: read # To push a branch
      pages: write # To push to a GitHub Pages site
      id-token: write # To update the deployment status

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Necessary in order to have fetch_discourse_md.py available for mdbook-cmd
      - name: Add docs/utils to PATH
        run: |
          echo $PWD/utils:$PATH >> $GITHUB_PATH

      - name: Build book
        uses: ./.github/workflows/build_mkdocs
        with:
          site_url: ${{ env.SITE_URL }}
          repo_url: ${{ env.REPO_URL }}
          working_dir: ${{ github.workspace }}
          output_dir: ${{ github.workspace }}/book
          upload_github_page: "true"
          github_token: ${{ github.token }}

  clean_cache:
    needs: deploy
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cache Cleanup
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          set -x
          old_caches=($(gh cache list \
            --repo ${{ github.repository }} \
            --key "${{ runner.os }}-build-${{ env.cache-mkdocs-key }}-"  \
            --sort created_at -O asc --json id | jq '.[:-1][].id'))
          for id in "${old_caches[@]}"; do
            gh cache delete $id
          done
      - name: Remove Page Artifacts
        uses: remagpie/gha-remove-artifact@v1
        with:
          only-name: github-pages
          max-age: 7776000 # 90 days
          max-count: 50
